[package]
name = "fogmesh"
version = "0.1.0"
edition = "2021"


[lib]
name = "fogmesh"
path = "src/lib.rs"

[[bin]]
name = "fogmesh"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"